### ISSUE TITLE
Typo: 'deTete' vs 'deLete'

### ISSUE THREAD

**Issue by yenemy** [fullstack-team-eagle-Grace-Shopper/Grace-Shopper#10]
Lots of other stuff in this file needs fixing too, but I assume this is an interim version while you guys figure out the `cart_inventory` stuff? I'm going to assume that's the case, and just do surface level spot reviews for now.

https://github.com/fullstack-team-eagle-Grace-Shopper/Grace-Shopper/blob/764b184b700c429fed9eb10130825156a0766cd3/db/models/cart.js#L43

**Comment by GabrielGuild** [comment]
deTETE
