### ISSUE TITLE
Forgot to do this? Or have you just not committed the code yet?

### ISSUE THREAD

**Issue by yenemy** [fullstack-team-eagle-Grace-Shopper/Grace-Shopper#17]
Just making sure

https://github.com/fullstack-team-eagle-Grace-Shopper/Grace-Shopper/blob/ed5715e9febb8d282ea19e721ba9d215e299c001/api/cart.js#L3

**Comment by joegarrett404** [comment]
We've changed the way we're handling the carts and orders, so /api/cart.js and /db/models/cart.js will probably be removed
