### ISSUE TITLE
Broken endpoint

### ISSUE THREAD

**Issue by yenemy** [fullstack-team-eagle-Grace-Shopper/Grace-Shopper#23]
This is a broken reference; `getCartInventoryByUserId` is not a function. Guessing you meant `getCartByUserId` ?

https://github.com/fullstack-team-eagle-Grace-Shopper/Grace-Shopper/blob/6510afdfdf7f146897207572de7e11a63e50df89/api/users.js#L138

**Comment by joegarrett404** [comment]
Yes... fixed it
