### ISSUE TITLE
Functional bug: adding more items than exist in stock still goes through to the cart

### ISSUE THREAD

**Issue by yenemy** [fullstack-team-eagle-Grace-Shopper/Grace-Shopper#37]
Bugged workflow:
- Click an inventory item
- Add >10 items to my cart
- I get an alert saying there isn't enough stock (good!)
- >10 items are still added to my cart (bad!)

Desired workflow:
- The items should not be added to my cart after the alert

**Comment by joegarrett404** [comment]
We believe we have fixed this bug
