### ISSUE TITLE
Categories usually have a many-to-many relationship with products; you might want to consider a different table structure here

### ISSUE THREAD

**Issue by yenemy** [fullstack-team-eagle-Grace-Shopper/Grace-Shopper#5]
https://github.com/fullstack-team-eagle-Grace-Shopper/Grace-Shopper/blob/2da83b4b4a3a5694099b836d3c694c7fca3e5c62/db/seed.js#L37

A many-to-many relationship basically means something like this:
- any given product might have multiple categories
- any given category might have multiple products

The classic database table structure for relationships like this is a junction table, like:
- `categories` table
- `products` table
- `product_categories` table (or `category_products`)

**Comment by GabrielGuild** [comment]
problem seems to be resolved
