### ISSUE TITLE
Think about how you want your shopping cart to work, and/or what features it needs

### ISSUE THREAD

**Issue by yenemy** [fullstack-team-eagle-Grace-Shopper/Grace-Shopper#7]
Currently, your shopping cart only supports a single product; for example, someone could buy 1 table, or 5000 cutting boards, but not a table and a cutting board at the same time.

If that's something you'd want to support (and most shopping carts in my experience do), you would need to consider allowing a one-to-many relationship between your carts and products. This might involve another junction table.

https://github.com/fullstack-team-eagle-Grace-Shopper/Grace-Shopper/blob/bc759d63227a79c21af0575c60554b3a5b2ca810/db/seed.js#L49-L56

**Comment by joegarrett404** [comment]
I think we have this functioning now
